schema: manus_l20.flexion_calibration.v1
finger_order:
- thumb
- index
- middle
- ring
- pinky
root_flexion_open_rad:
- 0.012372
- 0.06993
- 0.147572
- 0.125734
- 0.490954
root_flexion_closed_rad:
- 0.012372
- 1.798558
- 2.022632
- 1.986314
- 1.796543
tip_flexion_open_rad:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
tip_flexion_closed_rad:
- 0.0
- 1.909802
- 2.284685
- 2.072607
- 1.558818
root_flexion_direction_sign:
- 1.0
- -1.0
- -1.0
- -1.0
- -1.0
tip_flexion_direction_sign:
- 1.0
- -1.0
- -1.0
- -1.0
- -1.0
command:
  open_command:
  - 160    # 0  Thumb Base / 拇指根部弯曲
  - 255    # 1  Index Finger Base / 食指根部弯曲
  - 255    # 2  Middle Finger Base / 中指根部弯曲
  - 255    # 3  Ring Finger Base / 无名指根部弯曲
  - 255    # 4  Pinky Finger Base / 小指根部弯曲
  - 150    # 5  Thumb Roll / 拇指 roll
  - 163    # 6  Index Finger Yaw / 食指侧摆
  - 129    # 7  Middle Finger Yaw / 中指侧摆
  - 86     # 8  Ring Finger Yaw / 无名指侧摆
  - 62     # 9  Pinky Finger Yaw / 小指侧摆
  - 255    # 10 Thumb Yaw / 拇指 yaw
  - 255    # 11 Reserved / 保留位
  - 255    # 12 Reserved / 保留位
  - 255    # 13 Reserved / 保留位
  - 255    # 14 Reserved / 保留位
  - 220    # 15 Thumb Tip / 拇指指尖弯曲
  - 255    # 16 Index Finger Tip / 食指指尖弯曲
  - 255    # 17 Middle Finger Tip / 中指指尖弯曲
  - 255    # 18 Ring Finger Tip / 无名指指尖弯曲
  - 255    # 19 Pinky Finger Tip / 小指指尖弯曲
  four_finger_closed_command:
  - 160    # 0  Thumb Base / 拇指根部弯曲
  - 13     # 1  Index Finger Base / 食指根部弯曲
  - 0      # 2  Middle Finger Base / 中指根部弯曲
  - 5      # 3  Ring Finger Base / 无名指根部弯曲
  - 15     # 4  Pinky Finger Base / 小指根部弯曲
  - 128    # 5  Thumb Roll / 拇指 roll
  - 128    # 6  Index Finger Yaw / 食指侧摆
  - 128    # 7  Middle Finger Yaw / 中指侧摆
  - 128    # 8  Ring Finger Yaw / 无名指侧摆
  - 128    # 9  Pinky Finger Yaw / 小指侧摆
  - 255    # 10 Thumb Yaw / 拇指 yaw
  - 255    # 11 Reserved / 保留位
  - 255    # 12 Reserved / 保留位
  - 255    # 13 Reserved / 保留位
  - 255    # 14 Reserved / 保留位
  - 110    # 15 Thumb Tip / 拇指指尖弯曲
  - 12     # 16 Index Finger Tip / 食指指尖弯曲
  - 12     # 17 Middle Finger Tip / 中指指尖弯曲
  - 2      # 18 Ring Finger Tip / 无名指指尖弯曲
  - 9      # 19 Pinky Finger Tip / 小指指尖弯曲
samples:
  open:
    root_rad:
    - 0.012372
    - 0.06993
    - 0.147572
    - 0.125734
    - 0.490954
    tip_rad:
    - 0.350714
    - 0.014915
    - 0.083727
    - 0.131415
    - 0.231189
    root_signed_rad:
    - 0.012372
    - -0.06993
    - -0.147572
    - -0.125734
    - -0.490954
    tip_signed_rad:
    - -0.350714
    - 0.014915
    - 0.083727
    - 0.131415
    - 0.231189
  four_finger_fist:
    root_rad:
    - 0.239607
    - 1.798558
    - 2.022632
    - 1.986314
    - 1.796543
    tip_rad:
    - 0.162084
    - 1.909802
    - 2.284685
    - 2.072607
    - 1.558818
    root_signed_rad:
    - 0.239607
    - -1.798558
    - -2.022632
    - -1.986314
    - -1.796543
    tip_signed_rad:
    - -0.162084
    - -1.909802
    - -2.284685
    - -2.072607
    - -1.558818
