schema: manus_l20.thumb_flexion_mapping.v1
finger: thumb
root_flexion_direction_sign: 1.0
tip_flexion_direction_sign: 1.0
command:
  thumb_natural_open_command:
  - 160
  - 255
  - 255
  - 255
  - 255
  - 150
  - 163
  - 129
  - 86
  - 62
  - 255
  - 255
  - 255
  - 255
  - 255
  - 220
  - 255
  - 255
  - 255
  - 255
  thumb_pinky_root_touch_command:
  - 60
  - 255
  - 255
  - 255
  - 255
  - 0
  - 163
  - 129
  - 86
  - 62
  - 100
  - 255
  - 255
  - 255
  - 255
  - 120
  - 255
  - 255
  - 255
  - 255
samples:
  thumb_pinky_root_touch:
    root_rad: 0.419335
    tip_rad: 0.548298
    root_signed_rad: 0.419335
    tip_signed_rad: 0.548298
  thumb_natural_open:
    root_rad: 0.0
    tip_rad: 0.0
    root_signed_rad: -8.2e-05
    tip_signed_rad: -0.035859
