retargeting:
  type: vector
  preset: universal
  vector_loss:
    type: direction
    huber_delta: 0.02
    scaling: 1.0
    scale_landmarks:
    - 0
    - 9
    scale_bodies:
    - middle_base
    - middle_tip
    scale_body_types:
    - body
    - site
  preprocess:
    temporal_filter_alpha: 0.65
  solver:
    max_iterations: 60
    norm_delta: 0.001
    output_alpha: 0.92
